#!/bin/sh

# Copyright 2018 Marcos Rafael Kaissi Barbosa
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# More about startup order:
#   https://docs.docker.com/compose/startup-order/
# More about ORACLE health check and Dockerfile:
#   https://oracle-base.com/articles/linux/docker-writing-your-first-dockerfile
# More about SQLPLUS output:
#   https://dba.stackexchange.com/questions/54149/how-to-make-sqlplus-output-appear-in-one-line
# SQLPLUS System Variable Summary:
#   https://docs.oracle.com/cd/E11882_01/server.112/e16604/ch_twelve040.htm

if [ ! -f /.start_healthcheck ]; then
    exit 1
fi

result=`su oracle -c "${ORACLE_HOME}/bin/sqlplus -s / as sysdba" <<EOF
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT 'OK' FROM DUAL;
EXIT
EOF`

if [ "${result}" = "OK" ]; then
    exit 0
else
    exit 1
fi